### ISSUE TITLE
Does not serialize HttpError

### ISSUE THREAD

**Issue by kwaclaw** [WebApiContrib/WebApiContrib.Formatting.ProtoBuf#2]
Assuming content negotiation selects protobuf, then a HttpError object would need to be serialized accordingly. This scenario gets triggered when I return an error response like this:

    Request.CreateErrorResponse(System.Net.HttpStatusCode.BadRequest, errMsg);

The problem is that HttpError cannot be serialized by protobuf-net as it has "object" as type parameter, and surrogates cannot be used, because HttpError  derives from Dictionary and protobuf-net does not allow surrogates for collections.

Not sure how to fix this.

**Comment by filipw** [comment]
this is resolved in #7 

`ProtoContractAttribute` is mandatory on the return type

**Comment by hastarin** [comment]
This is closed but no new NuGet package has been published.  Is there any chance we'll get a new one with this fix included?

**Comment by hastarin** [comment]
NOTE: I copied the current code into my project and now a simple List<int> within a type prevents it from being available.
